[coverage]
# 包含所有 .mjs 文件
include = ["**/*.mjs"]
# 排除不需要检查的文件或目录
exclude = [
    "**/node_modules/**",
    "**/test/**", # 排除测试文件本身，除非您也想测试测试文件
    "**/coverage/**" # 排除生成的覆盖率报告目录
]
# 指定报告的格式。Codecov 通常需要 lcov
reporter = ["lcov", "text"]