export const LINTER_SUPPORTED_FILE = {
  biome: [".js", ".jsx", ".ts", ".tsx", ".json"],
  eslint: [".js", ".jsx", ".ts", ".tsx", ".vue"],
  oxlint: [".js", ".jsx", ".ts", ".tsx"],
  prettier: [".js", ".jsx", ".ts", ".tsx", ".json", ".css"],
  pylint: [".py"],
  flake8: [".py"],
  black: [".py"],
  isort: [".py"],
  mypy: [".py"],
  shellcheck: [".sh", ".bash", ".dash", ".ksh"],
  "golangci-lint": [".go"],
  rubocop: [".rb", ".rake", ".gemfile"],
  hadolint: ["Dockerfile", ".dockerfile"],
  yamllint: [".yml", ".yaml"],
  stylelint: [".css", ".scss", ".sass"],
};
export const SUFFIX_TO_CODE_LANGUAGE = {
  ".js": ["js", "javascript", "node"],
  ".jsx": ["jsx"],
  ".ts": ["ts", "typescript"],
  ".tsx": ["tsx"],
  ".json": ["json"],
  ".vue": ["vue"],
  ".css": ["css"],
  ".py": ["python", "python3"],
  ".sh": ["shell", "sh", "shell-script", "bash", "zsh"],
  ".go": ["go", "golang"],
  ".rb": ["ruby", "jruby", "macruby", "rake", "rb", "rbx"],
  ".dockerfile": ["dockerfile"],
  ".yml": ["yaml", "yml"],
  ".sass": ["sass"],
  ".scss": ["scss"],
};

export const CODE_LANGUAGE_MAP_LINTER = {
  js: "biome-lint",
  javascript: "biome-lint",
  node: "biome-lint",
  jsx: "biome-lint",
  ts: "biome-lint",
  typescript: "biome-lint",
  tsx: "biome-lint",
  json: "biome-lint",
  vue: "eslint",
  css: "prettier",
  python: "flake8",
  python3: "flake8",
  shell: "shellcheck",
  sh: "shellcheck",
  "shell-script": "shellcheck",
  bash: "shellcheck",
  zsh: "shellcheck",
  go: "golangci-lint",
  golang: "golangci-lint",
  ruby: "rubocop",
  jruby: "rubocop",
  macruby: "rubocop",
  rake: "rubocop",
  rb: "rubocop",
  rbx: "rubocop",
  dockerfile: "hadolint",
  yaml: "yamllint",
  yml: "yamllint",
  sass: "stylelint",
  scss: "stylelint",
};

export const CODE_LANGUAGE_MAP_SUFFIX = {
  js: ".js",
  javascript: ".js",
  node: ".js",
  jsx: ".jsx",
  ts: ".ts",
  typescript: ".ts",
  tsx: ".tsx",
  json: ".json",
  vue: ".vue",
  css: ".css",
  python: ".py",
  python3: ".py",
  shell: ".sh",
  sh: ".sh",
  "shell-script": ".sh",
  bash: ".sh",
  zsh: ".sh",
  go: ".go",
  golang: ".go",
  ruby: ".rb",
  jruby: ".rb",
  macruby: ".rb",
  rake: ".rb",
  rb: ".rb",
  rbx: ".rb",
  dockerfile: ".dockerfile",
  yaml: ".yml",
  yml: ".yml",
  sass: ".sass",
  scss: ".scss",
};

export const DEDUCT_ERROR = 10;
export const DEDUCT_WARNING = 5;
