# Project information for page publishing
projectName: aigne-doc-smith
projectDesc: AIGNE DocSmith is a powerful, AI-driven documentation generation
  tool built on the AIGNE Framework. It automates the creation of detailed,
  structured, and multi-language documentation directly from your source code.
projectLogo: https://avatars.githubusercontent.com/u/143965177?v=4
projectSlug: aigne-doc-smith-v1

# =============================================================================
# Website Configuration
# =============================================================================

# Purpose: What's the main outcome you want readers to achieve?
# Available options (uncomment and modify as needed):
#   landingPage      - Landing page / Homepage: Convert visitors into users or customers
#   ecommerce        - E-commerce / Online store: Sell products or services online
#   portfolio        - Portfolio / Showcase: Display creative work, projects, or achievements
#   corporate        - Corporate / Business: Professional business website with company information
#   blog             - Blog / Content site: Share articles, news, and regular content updates
#   saas             - SaaS / Software product: Promote and onboard users to software services
#   nonprofit        - Non-profit / Community: Promote causes, accept donations, engage volunteers
#   education        - Educational / Learning: Provide courses, tutorials, or educational content
#   mixedPurpose     - Multi-purpose website: Comprehensive website covering multiple needs
pagePurpose:
  - landingPage
  - saas

# Target Audience: Who will be reading this most often?
# Available options (uncomment and modify as needed):
#   customers        - Customers / End users: People who buy or use your products/services
#   businessOwners   - Business owners / Entrepreneurs: People running businesses looking for solutions
#   marketers        - Marketing teams: People promoting products or managing campaigns
#   designers        - Designers / Creative professionals: People focused on visual design and user experience
#   developers       - Developers / Technical users: People building or integrating technical solutions
#   investors        - Investors / Stakeholders: People evaluating business potential and growth
#   jobSeekers       - Job seekers / Potential employees: People looking for career opportunities
#   students         - Students / Learners: People seeking educational content or resources
#   generalPublic    - General public / Mixed audience: Broad audience with varied interests and backgrounds
targetAudienceTypes:
  - customers
  - developers

# Website Scale: How many pages should your website have?
# Available options (uncomment and modify as needed):
#   singlePage         - Single Page (only 1 page): All content consolidated into 1 page
#   minimal            - Minimal (2-6 pages): Core pages only - quick to launch
#   standard           - Standard (7-12 pages): Complete website with main sections [RECOMMENDED]
#   comprehensive      - Comprehensive (12+ pages): Full-featured website with detailed sections
#   aiDecide           - Let AI decide: Analyze project complexity and suggest appropriate scale
websiteScale: minimal

# Custom Rules: Define specific page generation rules and requirements
rules: ""

# Glossary: Define project-specific terms and definitions
# glossary: "@glossary.md"  # Path to markdown file containing glossary definitions

locale: en
translateLanguages:
  - zh
pagesDir: .aigne/web-smith/pages  # Directory to save generated pages
sourcesPath:  # Source code paths to analyze
  - ./README.md
  - ./media.md
  - ./docs/advanced-how-it-works.md
  - ./docs/cli-reference.md
  - ./docs/getting-started.md
lastGitHead: 00fdcff5a2a9c7b56d670013bb26ac88f2c4b4bc
# Checkout ID for website deployment service
checkoutId: ""
# Payment URL for website deployment service
paymentUrl: https://s.aigne.io/VU0JAUL7
appUrl: https://baaaub7cqxqgchexrtl6ovx52ecjexruwlk2bvzmhmu.slp.abtnet.io
projectId: ffe60b0f-a663-4a3b-b55e-c8d7cb5fb07e
